# Tarea día 8
**Programación I**

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [2]:
import numpy as np

N = 100      # Se debe ingresar un número
k = N//2
arr = np.array([0]*k+([1]*(N-k)))
arr2 = np.random.shuffle(arr)
# Se debe configurar el tamaño de la matriz, para que albergue los N número
arr3 = arr.reshape(10,10)
arr3

array([[1, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 1, 1, 1, 1, 0, 1, 0],
       [0, 0, 1, 1, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 1, 0, 1, 1, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 1, 1, 0, 0, 1, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 1, 1, 1],
       [0, 0, 1, 0, 0, 0, 0, 1, 1, 0]])

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 


In [1229]:
# Ejercicio 2
p = np.zeros((5,2), dtype = np.int16)    # Primera matriz con ceros
p


array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

In [1100]:
r = p.reshape(10,1)
r


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=int16)

In [1103]:
r.shape

(10, 1)

In [1104]:
q = np.ones((5,2), dtype= np.int16)       # Segunda matriz con unos
q

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [1105]:
f1 = p.flatten()        # Arreglo de ceros en una dimensión
f1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [1106]:
f2= q.flatten()         # Arreglo de unos en una dimensión
f2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [1107]:
# Subejercicio.1 Vectores Columna
vc1 = (f1[: , None])    
vc1

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=int16)

In [1108]:
vc2 = (f2[:,None])
vc2

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int16)

In [1109]:
vc1.shape  # Validando que se trata de un vector columna de nxm dimensiones

(10, 1)

In [1110]:
vc2.shape  # Validando que se trata de un vector columna de nxm dimensiones

(10, 1)

In [1111]:
#Subjercicio.2 Apilar vector col en 3 dimensiones
np.dstack((vc1,vc2))

array([[[0, 1]],

       [[0, 1]],

       [[0, 1]],

       [[0, 1]],

       [[0, 1]],

       [[0, 1]],

       [[0, 1]],

       [[0, 1]],

       [[0, 1]],

       [[0, 1]]], dtype=int16)

In [1112]:
np.dstack((vc1,vc2)).ndim  # validación que apilación está en 3 dimensiones

3

In [1113]:
#Subjercicio.3 Vectores filas
vf1 = vc1.T   # Vectores fila de ceros a partir de los vectores columna.
vf1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

In [1114]:
pvf = p.reshape(1,10) # Opción 2
pvf

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

In [1115]:
vf1.shape      # Validación de que se trata de un vector fila

(1, 10)

In [1116]:
vf2 = vc2.T   # Vectores fila de ceros a partir de los vectores columna.
vf2

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [1117]:
np.vstack((p,q))

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [1118]:
vf2.shape       # Validación de que se trata de un vector fila

(1, 10)

In [1119]:
np.concatenate((vf1,vf2), axis=0) # Opción 1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [1120]:
np.vstack((vf1,vf2))      # Opción 2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios, donde cada columna sea una variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser una vector columna. 

In [5]:
def f(x,y,z):                   # definiendo la matriz
    return 2*x + 3*y + z**2

In [6]:
# Dimensinoes de las matrices, debe tener 3 columnas para que cada una sea x, y, z
n = 4     
m = 3

matrizAl = np.random.randint(100,size=([n,m]))   
matrizAl

array([[75,  6, 99],
       [23, 81,  4],
       [28, 63, 70],
       [51, 40, 96]])

In [7]:
matrizAl.ndim

2

In [8]:
# Se obtiene el listado para x, y y el z
x = matrizAl[:,0]    
y = matrizAl[:,1]
z = matrizAl[:,2]

eval = f(x,y,z)
vcolEval = eval.reshape(n,1)    # Para presentar como vector columna
vcolEval 

array([[9969],
       [ 305],
       [5145],
       [9438]])

## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [808]:
cExt = np.random.choice(2,2500).reshape(50,50)   # Matriz de 50x50, colocando 0 y 1
cExt

array([[0, 1, 0, ..., 0, 1, 0],
       [1, 0, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 0],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 0, 0],
       [1, 1, 0, ..., 1, 0, 1]])

In [809]:
sExt = cExt.sum()     # Se calcula el número de puntos que tiene el cuadrado exterior
sExt

1277

In [810]:
cInt = cExt[15:35,15:35]   # Se calcula el número de puntos que tiene el cuadrado interior
cInt                       # tomando como punto inicial el 15, porque se le quitan 15 de cada lado, y de 15 a 35 hay 20 espacios

array([[1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1],
       [0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1],
       [1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1],
       [0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 0, 0, 0, 1, 1, 1,

In [811]:
sInt = cInt.sum()
sInt

201

In [812]:
cInt=cEnt[15:35,15:35]
cInt

array([[1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1],
       [1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
       [0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1],
       [1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0],
       [1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 1,

In [813]:
Proporc = sInt/sExt 
Proporc

0.15740015661707127

El área del objeto se calcula como:

> Area object = area of rectangle x number of points inside object/total number of points in rectangle



In [814]:
areaObj=((50*50)*Proporc)   # el cuadrado exterior tienen dim 50x50
areaObj

393.5003915426782

## Ejercicio 5

### *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

### Subejercicio 1.

In [854]:
# 1. numpy.identity(n, dtype=None): 
""" 
Regresa una matriz identidad, con ceros en la diagonal principal.
"""

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [853]:
# 2. numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C'): 
"""
Regresa un arreglo con unos en la diagonal indicada y ceros 
"""

np.eye(6, k=-2)   # un valor positivo de k se ubica en la diagonal superior, y un valor negativo en la diagonal inferior.

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [852]:
# 3. numpy.ones & numpy.zeros(shape, dtype=None, order='C'): 
"""
Ambas regresan un arreglo con una forma dada con la diferencia que 
la primera lo hace rellena de ceros y la segunda rellena de unos.
"""

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [851]:
# 4. numpy.full(shape, fill_value, dtype=None, order='C):
"""
Regresa un nuevo arreglo dada una forma y un tipo, rellenada con un
fill_value
"""

np.full((2, 2), ["hola", 4])

array([['hola', '4'],
       ['hola', '4']], dtype='<U4')

In [850]:
# 5. numpy.empty(shape, dtype=float, order='C'):
"""
Regresa un nuevo arreglo dada una forma y un tipo, sin valores de entrada.
"""

np.empty([3,3])

array([[2.12199579e-314, 0.00000000e+000, 4.94065646e-324],
       [4.94065646e-324, 2.12199579e-314, 2.12199579e-314],
       [2.12199579e-314, 2.12199579e-314, 4.94065646e-324]])

In [857]:
# 6. numpy.asarray(a, dtype=None, order=None):
"""
Convierte una entrada en un arreglo.
"""

b = {"A":10, "B":20, "C":30, "D": 40}
np.asarray(b)

# dtype se pone, el arreglo se copia sólo si dtype no coincide.

array({'A': 10, 'B': 20, 'C': 30, 'D': 40}, dtype=object)

In [885]:
# 7. numpy.asanrray(a, dtype=None, order=None):
"""
Convierte una entrada en un arreglo, pero sí pasa las subclases del arreglo.
"""

a = np.array([(3.5, 8), (2.73, 4)], dtype='f4,i4').view(np.recarray)
np.asanyarray(a) is a

True

In [900]:
# 8. numpy.asmatrix(data, dtype=None):
"""
Interpreta una entrada como una matriz.
"""

j = np.array([[1,2],[4,6],[7,3]])
m = np.asmatrix(j)
j[2,1]=29
m

matrix([[ 1,  2],
        [ 4,  6],
        [ 7, 29]])

In [983]:
# 9. numpy.copy(a, order='K'):
"""
Regresa una copia del arreglo de una objeto dado.
"""
#Considere una reglo con x, referenciado a y, creando una copia z:
x = np.random.choice(2,25)
y = x
z = np.copy(x)
x

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1])

In [986]:
#Al modificar x, y cambia pero no lo hace z.
x[4] = 5
x[4] == y[4]

True

In [987]:
x[4] == z[4]

False

In [1015]:
# 10. numpy.fromfunction(function, shape, *, dtype=<class 'float'>, **kwargs):
"""
Construye un arreglo ejecutando una función sobre cada coordenada de la matriz.
La matriz resultante por lo tanto tiene valor fn(x,y,z) en la coordenada (x,y,z).

"""
def f(x,y):
    return 5*x + y**2
a = np.fromfunction(f, (6,4), dtype=int)
a

array([[ 0,  1,  4,  9],
       [ 5,  6,  9, 14],
       [10, 11, 14, 19],
       [15, 16, 19, 24],
       [20, 21, 24, 29],
       [25, 26, 29, 34]])

In [1017]:
# 11. numpy.fromiter(iterable, dtype, count=1):
"""
Crea un arreglo unidimensional de un objeto iterable.
"""

iterable = (x*x for x in range(6))
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16., 25.])

In [1025]:
# 12. numpy.fromstring(string, dtype=float, count=1, sep=''):
"""
Se inicia un arreglo unidimensional de texto en una cadena.
"""

np.fromstring('1 2 3 4 5', dtype=int, sep=' ')

array([1, 2, 3, 4, 5])

In [1028]:
# 13. numpy.loadtxt:
"""
Carga la información de un archivo de texto.
Cada fila in el archivo de texto debe tener el mismo número de valores. 
"""

from io import StringIO   # StringIO behaves like a file object
s = StringIO(u"0 3 5\n4 7 5")
np.loadtxt(s)

array([[0., 3., 5.],
       [4., 7., 5.]])

In [1058]:
# 14. numpy.core.records.fromarrays(arrayList, dtype=None, shape=None, formats=None, names=None, titles=None, aligned=False, byteorder=None):
"""
Crea una matriz de registros a partir de una lista plana de arreglos.
"""

x1 = np.array([17,23,1])
x2 = np.array(['a','ddd','12'])
x3 = np.array([5.5,2,7.5])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])

(23, 'ddd', 2.)


In [1061]:
# 15. numpy.arange([start, ]stop, [step, ]dtype=None):
"""
Regresa valores con un espacio uniforme dentro de un intervalo dado.
Los valores se generan dentro del intervalo medio abierto[inicio, fin)
Para argumentos enteros, la función es equivalente a la función de rango 
usada en el paquete base, pero devuelve un ndarray en lugar de una lista.

Nota: Cuando se usa un step no entero, el resultado no será consistente, 
se recomienda usar numpy.linspace para estos casos. 
"""

np.arange(3,25,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [1066]:
# 16. numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0):
"""
Regresa valores con un espacio uniforme dentro de un intervalo dado.
Devuelve num muestras espaciadas uniformemente, calculadas sobre el intervalo
[inicio, stop], el punto final del intervalo puede excluirse opcionalmente.
"""

np.linspace(2.4,5, num=4)

array([2.4       , 3.26666667, 4.13333333, 5.        ])

In [1077]:
np.linspace(2.4,4.5, num=5, retstep=True)

(array([2.4  , 2.925, 3.45 , 3.975, 4.5  ]), 0.525)

In [1129]:
# 17. numpy.mgrid = <numpy.lib.index_tricks.MGridClass object>:
"""
Devuelve una malla de malla multidimensional cuando está indexada para que 
cada argumento devuelto tenga la misma forma. 
"""

np.mgrid[0:5,:4]

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [1131]:
# 18. numpy.ogrid = <numpy.lib.index_tricks.OGridClass object>:
"""
Devuelve una malla de mallas multidimensionales abierta.
"""
from numpy import ogrid
ogrid[-1:1:5j]

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [1132]:
ogrid[0:5,1:4]

[array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[1, 2, 3]])]

In [1134]:
# 19. numpy.diag(v, k=0):
"""
Extrae una diagonal o construye una matriz diagonal.
"""

j = np.arange(20).reshape(4,5)
j

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [1135]:
np.diag(j)

array([ 0,  6, 12, 18])

In [1136]:
np.diag(j, k=2)

array([ 2,  8, 14])

In [1138]:
np.diag(np.diag(j))

array([[ 0,  0,  0,  0],
       [ 0,  6,  0,  0],
       [ 0,  0, 12,  0],
       [ 0,  0,  0, 18]])

In [1148]:
# 20. numpy.diagflat(v, k=0):
"""
Crea una matriz de bidimensional con la entrada aplanada (flattened input)
como una diagonal.
"""
np.diagflat([[6,2],[20,5],[6,7]])

array([[ 6,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0],
       [ 0,  0, 20,  0,  0,  0],
       [ 0,  0,  0,  5,  0,  0],
       [ 0,  0,  0,  0,  6,  0],
       [ 0,  0,  0,  0,  0,  7]])

In [1158]:
np.diagflat([6,5], -2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [6, 0, 0, 0],
       [0, 5, 0, 0]])

In [1163]:
# 21. numpy.tri(N, M=None, k=0, dtype=<class 'float'>):
"""
Devuelve una matriz con unos debajo de la diagonal principal, y el resto con zeros.
"""

np.tri(5,7, -1)

array([[0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.]])

In [1177]:
# 22. numpy.tril(m, k=0):
"""
Triángulo inferior de una matriz. Devuelve una copia de una 
matriz con elementos por encima de la diagonal k-ésima puesta a cero.
"""

np.tril([[1,2,3],[4,9,6],[7,34,9],[2,21,12]], -2)

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 7,  0,  0],
       [ 2, 21,  0]])

In [1179]:
# 23. numpy.triu(m, k=0):
"""
Triángulo superior de una matriz. Devuelve una copia de una matriz con los 
elementos debajo de la diagonal k-ésima puesta a cero.
"""

np.triu([[1,2,3],[4,9,6],[7,34,9],[2,21,12],[2,1,87]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [1185]:
# 24. numpy.mat(data, dtype=None):
"""
Interpreta la entrada como una matriz. A diferencia de la matriz, asmatriz 
no hace una copia si la entrada ya es una matriz o un ndarray. Equivalente
a la matriz (datos, copia=False)
"""

h = np.array([[1,2],[3,5]])
m = np.asmatrix(h)
h[1,1]=17
m

matrix([[ 1,  2],
        [ 3, 17]])

In [1189]:
# 25. numpy.bmat(obj, ldict=None, gdict=None):
"""
Construye un objeto de una matriz a partir de una cadena, secuencia anidada
o una matriz.
"""
A = np.mat('1 1; 1 1')
B = np.mat('2 2; 2 2')
C = np.mat('3 4; 5 6')
D = np.mat('7 8; 9 0')

np.bmat([[A,B],[C,D]])

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [1190]:
# 26. numpy.shape(a):
"""
Devuelve la forma de una matriz.
"""

q = np.ones((5,2), dtype= np.int16)       # Segunda matriz con unos
q.shape

(5, 2)

In [1210]:
# 27. numpy.reshape(a, newshape, order='C'):
"""
Devuelve una nueva forma para una matriz sin cambiar su data. 
"""

a = np.random.randint(100,size=([4,5]))
b = a.reshape(10,2)
b

array([[84, 40],
       [75, 83],
       [63, 53],
       [63, 74],
       [38, 40],
       [28, 80],
       [46, 64],
       [36, 67],
       [45, 77],
       [78, 52]])

In [1209]:
c = a = np.array([[1,2,3], [4,5,6]])
np.reshape(c, 6, order='F')

array([1, 4, 2, 5, 3, 6])

In [1217]:
# 28. numpy.ravel(a, order='C'):
"""
Devuelve una matriz aplanada contigua.Se devuelve una matriz 
unidimensional que contiene los elementos de la entrada. Se realiza 
una copia sólo si es necesario. 
"""

a = np.arange(11)[::-1]; 
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [1228]:
# 29. numpy.ndarray.flat:
"""
Es un iterador unidimensional sobre la matriz.
"""

x = np.arange(1, 18, 2).reshape(3, 3)
x.flat[3]


7

In [1233]:
# 30. numpy.ndarray.flatten(order='C'):
"""
Devuelve una copia de una matriz contraída en una unidimensional.
"""

a = np.array([[1,4], [8,2]])
a.flatten('F')

array([1, 8, 4, 2])

In [1238]:
# 31. numpy.moveaxis(a, source, destination):
"""
Mueve los ejes de una matriz a  nuevas posiciones. Otros ejes permanecen
en su orden original.
"""

x = np.zeros((3, 4, 5))
np.moveaxis(x,-1,0).shape

(5, 3, 4)

In [1240]:
# 32. numpy.rollaxis(a, axis, start=0):
"""
Gire el eje especificado hacia atrás, hasta que se encuentre en una 
posición determinada. 
"""

a = np.ones((7,4,5,10,5))
np.rollaxis(a, 3, 1).shape

(7, 10, 4, 5, 5)

In [1245]:
# 33. numpy.swapaxes(a, axis1, axis2):
"""
Intercambia 2 ejes en una matriz.
"""

y = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
z = np.swapaxes(y,0,2)
z

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [1253]:
# 34. numpy.ndarray.T:
"""
Devuelve la matriz traspuesta. Es igual que self.transpose().
"""
x = np.array([[5,21,982],[4,3,12]])
x.T

array([[  5,   4],
       [ 21,   3],
       [982,  12]])

In [1257]:
# 35. numpy.transpose(a.axes=None):
"""
Invierta o permute los ejes de una matriz; Devuelve la matriz modificada. 
Para una matriz a con dos ejes, la transpuesta proporciona la matriz
transpuesta. 
"""

x = np.array([[5,21,982],[4,3,12]])
np.transpose(x)

array([[  5,   4],
       [ 21,   3],
       [982,  12]])

In [1260]:
# 36. numpy.atleast_1d(*arys):
"""
Convierte los inputs en matrices con al menos una dimensión. Las entradas
escalares se convierten en matrices unidimensionales, mientras que 
los inputs de más dimensiones se conservan. 
También están .atleast_2d y 3d para 2 y 3 dimensiones.
"""

np.atleast_1d(100.0)

array([100.])

In [1266]:
x = np.arange(16).reshape(4,4)
np.atleast_1d(x)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [1272]:
# 37. numpy.broadcast_to(array,shape,subok=False):
"""
Transmite una matriz a una nueva forma.
"""

x = np.array([3,4,5])
np.broadcast_to(x, (5, 3))

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [1276]:
# 38. numpy.broadcast_arrays(*args, subok=False):
"""
Transmite cualquier número de matrices entre sí. 
"""

n = np.array([[1,5,12]])
m = np.array([[3],[5],[1],[9]])
np.broadcast_arrays(n,m)

[array([[ 1,  5, 12],
        [ 1,  5, 12],
        [ 1,  5, 12],
        [ 1,  5, 12]]), array([[3, 3, 3],
        [5, 5, 5],
        [1, 1, 1],
        [9, 9, 9]])]

In [1282]:
# 39. numpy.expand_dims(a, axis):
"""
Expande la forma de una matriz. Inserta un nuevo eje que aparecerá en 
la posición del eje en la forma de matriz expandida.
"""
x = np.array([1, 2])
y = np.expand_dims(x, axis=0)
y

array([[1, 2]])

In [1285]:
# 40. numpy.squeeze(a,axis=None):
"""
Elimina entradas unidimensionales de la forma de una matriz.
"""

x = np.array([[[0], [1], [2]]])
np.squeeze(x)

array([0, 1, 2])

In [5]:
# 41. numpy.asarray(a, dtype=None, order=None):
"""
Convierte una entrada en una matriz
"""
c = {(1,2),(4,5),(6,9)}
np.asarray(c)


array({(1, 2), (6, 9), (4, 5)}, dtype=object)

In [6]:
# 42. numpy.asfarray(a, dtype=<class 'numpy.float64'>):
"""
Devuelve una matriz convertida en tipo float.
"""

np.asfarray([2, 3], dtype='float')

array([2., 3.])

In [15]:
# 43. nnumpy.afortranarray(a, dtype=None):
"""
Devuelve una matriz contigua unidimensional en orden fortran.
"""
f = np.arange(8).reshape(4,2)
np.asfortranarray(f)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [16]:
# 44. nnumpy.ascontiguousarray(a, dtype=None):
"""
Devuelve una matriz contigua unidimensional en orden c.
"""

e = np.arange(6).reshape(2,3)
np.ascontiguousarray(e, dtype=np.float32)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [17]:
# 45. numpy.asscalar(a):
"""
Convierte una matriz de tamaño 1 en su equivalente escalar.
"""

np.asscalar(np.array([17]))

17

In [19]:
# 46. numpy.concatenate(a1, a2, ...), axis=0, out=None):
"""
Une una secuencia de matrices a lo largo de los ejes existentes.
"""

j = np.array([[1, 2], [3, 4]])
o = np.array([[5, 6]])
np.concatenate((j,o), axis=0)   # La apilación es de forma vertical.

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
# 47. numpy.stack(arrays, axis=0, out=None):
"""
Une una secuencia de matrices a lo largo de un nuevo eje. El parámetro de 
eje especifica el índice del nuevo eje in la dimensión del resultado.
"""

o = np.array([1, 2, 3, 5])
p = np.array([2, 3, 4, 8])
np.stack((o, p), axis=-1)

array([[1, 2],
       [2, 3],
       [3, 4],
       [5, 8]])

In [23]:
# 48. numpy.colum_stack(tup):
"""
Stack matrices unidimensionales como columnas en una matriz bidimensional.
"""

a = np.array((1,2,3))
b = np.array((9,8,7))
np.column_stack((a,b))

array([[1, 9],
       [2, 8],
       [3, 7]])

In [26]:
# 49. numpy.dstack(tup):
"""
Stack matrices en una secuencia a lo largo de un tercer eje. Esto es 
equivalente a la concatenación a lo largo del tercer eje después 
de que las matrices bidimensionales de forma (m, n) se hayan reformado a 
(m, n, 1) y las matrices unidimensionales de forma (n,) se hayan reformado 
a (1, n, 1). Reconstruye matrices divididas por dsplit.
"""

a = np.array((9,8,7))
b = np.array((2,3,4))
c = np.dstack((a,b))
c

array([[[9, 2],
        [8, 3],
        [7, 4]]])

In [27]:
c.ndim   # Apilado en 3 dimensiones.

3

In [28]:
# 50. numpy.hstack(tup):
"""
Stack matrices en una secuencia horizontal(column wise).
"""

a = np.array((9,8,7))
b = np.array((2,3,4))
np.hstack((a,b))

array([9, 8, 7, 2, 3, 4])

In [29]:
# 51. numpy.vstack(tup):
"""
Stack matrices in una secuencia vertical(row wise).
"""

a = np.array((9,8,7))
b = np.array((2,3,4))
np.vstack((a,b))

revisar numpy.block

array([[9, 8, 7],
       [2, 3, 4]])

In [30]:
# 52. numpy.split(ary, indices_or_sections, axis=0):
"""
Parte una matriz en submatrices como vistas in ary.
"""

x = np.arange(12)
np.split(x, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [34]:
# 53. numpy.array_split(ary, indices_or_sections, axis=0):
"""
Parte una matriz en múltiples submatrices.
"""

y = np.arange(11)
np.array_split(y, 3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]

In [40]:
# 54. numpy.dsplit(ary, indices_or_sections):
"""
Parte una matriz en múltiples submatrices a lo largo del eje en tercera 
dimensión.
"""
g = np.arange(16).reshape(2, 2, 4)
g

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [41]:
np.dsplit(g,2)

[array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]), array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]])]

In [44]:
# 55. numpy.hsplit(ary, indices_or_sections):
"""
Parte un arreglo en submatrices horizontales(column-wise).
"""

z = np.arange(16).reshape(4, 4)
np.hsplit(z, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [45]:
# 56. numpy.vsplit(ary, indices_or_sections):
"""
Parte un arreglo en submatrices verticales(row-wise).
"""

z = np.arange(16).reshape(4, 4)
np.vsplit(z, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [47]:
# 57. numpy.repeat(a, repeats, axis=None):
"""
Repite elementos de una matriz.
"""

np.repeat(x, 3, axis=1)

array([[ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3],
       [ 4,  4,  4,  5,  5,  5,  6,  6,  6,  7,  7,  7],
       [ 8,  8,  8,  9,  9,  9, 10, 10, 10, 11, 11, 11],
       [12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15]])

In [48]:
# 58. numpy.delete(arr, obj, axis=None):
"""
Regresa una nueva matriz con submatrices a lo largo de un eje borrado. Para
matrices de una dimensión, regresa aquellas entradas que  no regresa arr[obj].
"""

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12],[20,19]])
np.delete(arr, 1,0)

array([list([1, 2, 3, 4]), list([9, 10, 11, 12]), list([20, 19])],
      dtype=object)

In [49]:
# 59. numpy.insert(arr, obj, axis=None):
"""
Inserta valores a lo largo de unos ejes dados antes de unos índices dados.
"""

c = np.array([[1, 1], [2, 2], [3, 3]])
c
np.insert(c, 1, 5)


array([1, 5, 1, 2, 2, 3, 3])

In [50]:
# 60. numpy.append(arr, obj, axis=None):
"""
Agrega valores al final de una arreglo.
Nota: When axis is specified, values must have the correct shape.
"""

np.append([[1, 2, 3], [56, 17, 12]], [[7, 8, 9]], axis=0)

array([[ 1,  2,  3],
       [56, 17, 12],
       [ 7,  8,  9]])

In [52]:
# 61. numpy.resize(a, new_shape):
"""
Devuelve una nueva matriz con una forma específica. Si la nueva matriz 
es más grande que la original, entonces este nuevo arreglo será llenado con
copias repetidas de a. Esto es diferente a a.resize(new_shape) que llena 
con ceros en lugar de copias repetidas de a. 
"""

a=np.array([[0,1],[2,3]])
np.resize(a,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [54]:
# 62. numpy.trim_zeros(filt, trim='fb')
"""
Recorta los ceros iniciales y/o finales de una matriz unidimensional o 
secuencia unidimensional.
"""
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trim_zeros(a)

array([1, 2, 3, 0, 2, 1])

In [58]:
# 63. numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None):
"""
Encuentra los elementos únicos de una matriz. Hay tres salidas opcionales
además de los elementos únicos:
- Los índices de la matriz de entrada que dan los valores únicos. 
- Los índices de la matriz única que reconstruye la matriz de entrada.
- La cantidad de veces que cada valor único aparece en la matriz de entrada
"""

a = np.array([[1, 1], [2, 3]])
np.unique(a)

array([1, 2, 3])

In [57]:
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
np.unique(a, axis=0)

array([[1, 0, 0],
       [2, 3, 4]])

In [67]:
# 64. numpy.flip(m, axis=None):
"""
Da la vuelta al orden de los elementos en una matriz a lo largo de un eje dado.
La forma de la matriz se mantiene, pero los elementos son reordenados.
"""

y = np.arange(8).reshape((2,2,2))
y

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [68]:
np.flip(y,1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [73]:
# 65. numpy.fliplr(m):
"""
Voltea la matriz en la dirección izquierda/derecha. Voltea las entradas en 
cada fila en la dirección izquierda/derecha. Las columnas se conservan, 
pero aparecen en un orden diferente al anterior.

Notes :Equivalent to m[:,::-1]. Requires the array to be at least 2-D.
"""
A = np.diag([1.,17.,3.,4.])
A

array([[ 1.,  0.,  0.,  0.],
       [ 0., 17.,  0.,  0.],
       [ 0.,  0.,  3.,  0.],
       [ 0.,  0.,  0.,  4.]])

In [74]:
np.fliplr(A)

array([[ 0.,  0.,  0.,  1.],
       [ 0.,  0., 17.,  0.],
       [ 0.,  3.,  0.,  0.],
       [ 4.,  0.,  0.,  0.]])

In [76]:
# 66. numpy.flipud(m):
"""
Voltea la matriz en la dirección arriba/abajo. Las filas son preservadas, 
pero aparecen en un diferente orden al previo. 
"""

B = [[0,2,4],[9,7,4],[4,2,9]]
np.flipud(B)

array([[4, 2, 9],
       [9, 7, 4],
       [0, 2, 4]])

In [80]:
# 67. numpy.reshape(a, newshape,order='C') 
"""
Le da una nueva forma a una matriz sin cambiar su información. 
"""

b = np.zeros((8, 3)).reshape(2,12)
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [84]:
# 68. numpy.roll(a, shift, axis=None):
"""
Roll los elementos de una matriz a lo largo de un eje dado. Los elementos que
van más allá de la última posición son reintroducidos al principio. 
"""

m = np.arange(8)
np.roll(m,-2)

array([2, 3, 4, 5, 6, 7, 0, 1])

In [87]:
# 69. numpy.rot90(m, k=1, axes=(0,1))
"""
Rotan una matriz en 90 grados en el plano especificado por los ejes.
La dirección de la rotación es desde el primer eje hasta el segundo eje. 
"""

m = np.arange(8).reshape((2,2,2))
m

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [89]:
np.rot90(m,1, (1,2))

array([[[1, 3],
        [0, 2]],

       [[5, 7],
        [4, 6]]])

In [93]:
# 70. numpy.char.compare_charrarrays(a, b, cmp_op, rstrip):
"""
Realiza una comparación entre elementos de do matrices con cadenas
utilizando el operador comparación especificado por cmp_op.
"""

a = np.array(["a","b","cdef"])
b = np.array(["a", "a", "fedc"])
np.compare_chararrays(a, b, ">", True)

array([False,  True, False])

In [96]:
# 71. numpy.char.upper(a):
"""
Devuelve una matriz con los elementos convertidos en letras mayúsculas. 
"""

c = np.array(['a1b c', '1bca', 'bca1']); 
np.char.upper(c)

array(['A1B C', '1BCA', 'BCA1'], dtype='<U5')

In [100]:
# 72. numpy.char.title(a):
"""
Devuelve la versión en cadena del título o unicode. 
Las palabras con mayúsculas y minúsculas comienzan con mayúsculas, 
todos los caracteres en mayúsculas restantes están en minúsculas.
"""

c=np.array(['a1b c','1b ca','b ca1','ca1b'],'S5'); 
np.char.title(c)

array([b'A1B C', b'1B Ca', b'B Ca1', b'Ca1B'], dtype='|S5')

In [102]:
# 73. numpy.char.count(a, sub, start=0, end=None):
"""
Devuelve una matriz con el número de ocurrencias no superpuestas de 
subcadenas sub en el rango [inicio, fin].
"""

k = np.array(['aAaAaA', '  aA  ', 'abBABba'])
np.char.count(k,"A")

array([3, 1, 1])

In [1286]:
# Subejercicio 4.
import numpy as np
x = 50 * np.random.random(10)

In [3]:
x

array([0.17720554, 0.76729411, 0.78628867, 0.99448786, 0.39297179,
       0.75922542, 0.56181402, 0.63047106, 0.81475668, 0.7412264 ])

In [8]:
x < 20

array([False,  True, False, False,  True, False, False, False,  True,
       False])

In [10]:
x = np.random.random((10, 2))
x

array([[0.98126291, 0.92447378],
       [0.22961204, 0.01737301],
       [0.37617547, 0.39387815],
       [0.84762065, 0.53757556],
       [0.28705701, 0.25260299],
       [0.09481289, 0.28244025],
       [0.17270721, 0.28945972],
       [0.33292029, 0.29791661],
       [0.36231345, 0.9590509 ],
       [0.97392281, 0.00300046]])

In [13]:
x[:,0]**2

array([0.9628769 , 0.05272169, 0.14150798, 0.71846077, 0.08240173,
       0.00898948, 0.02982778, 0.11083592, 0.13127104, 0.94852565])